#!/bin/bash

# 建议匹配到路径"/usr/local/bin/unpkg", 然后"chmod +x unpkg".
EXECUTABLENAME=$0
ARRTAG=([0]=".tar.gz"   [1]=".tar.bz2"  [2]=".gz"     [3]=".tar"      [4]=".Z"          [5]=".rar"     [6]=".7z"    [7]=".zip"  )
ARRCMD=([0]="tar -xzf " [1]="tar -xjf " [2]="gunzip " [3]="tar -xvf " [4]="uncompress " [5]="unrar e " [6]="7za x " [7]="unzip ")

GetCmdIdx()
{
    local fullName=${1}
    local baseName=""
    local suffix=""
    
    for((i=0;i<${#ARRTAG[*]};++i)); do
        suffix=${ARRTAG[${i}]}
        baseName=${fullName%${suffix}*}  # 参见"Shell十三问"
        if [ "${baseName}${suffix}" == "${fullName}" ]; then
            return ${i}
        fi
    done
    
    return ${#ARRTAG[@]}
}

DecompressionFile()
{
    local fileName=${1}
    GetCmdIdx ${fileName}
    local idx=$?
    if ((${#ARRTAG[*]} <= ${idx})); then
        echo ${EXECUTABLENAME}" FAIL(unrecognized archive), fileName="${fileName}
        return 255
    fi
    
    local cmd=${ARRCMD[${cmdIdx}]}
    ${cmd} ${fileName}
    local retVal=$?
    local retMsg="FAIL"
    if [ ${retVal} -eq 0 ]; then
        retMsg="SUCCESS"
    fi
    echo ${EXECUTABLENAME}" "${retMsg}"(decompression), cmd=["${cmd}${fileName}"]."
    
    return ${retVal}
}


if [ $# -lt 1 ]; then
    echo ${EXECUTABLENAME}" FAIL(no parameters)."
    exit 255
fi

DecompressionFile $1
